name: Code4Sac
description: We play with code
author: The Code4Sac Team
email:

baseurl: /
url:
permalink: pretty
timezone: "Pacific Time (US & Canada)"
encoding: utf-8

markdown: kramdown
kramdown:
  input: GFM